In [1]:
import torch

In [34]:
from glob import glob
glob('outputs/FT3/attentions/batch_11000.pt')

['outputs/FT3/attentions/batch_11000.pt']

In [70]:
i = 0
attns = torch.load(f'outputs/FT3/attentions/batch_{i}.pt')
logits = torch.load(f'outputs/FT3/logits/batch_{i}.pt')


In [71]:
attns.size()

torch.Size([32, 12, 184])

In [75]:
attns[:,-1,:][0].size()

torch.Size([184])

In [77]:
attn = attns[0][-1]
attn

tensor([0.0062, 0.0058, 0.0061, 0.0057, 0.0060, 0.0063, 0.0067, 0.0068, 0.0069,
        0.0063, 0.0064, 0.0061, 0.0032, 0.0040, 0.0030, 0.0037, 0.0040, 0.0035,
        0.0037, 0.0026, 0.0033, 0.0032, 0.0026, 0.0035, 0.0052, 0.0026, 0.0056,
        0.0067, 0.0072, 0.0069, 0.0070, 0.0064, 0.0067, 0.0066, 0.0079, 0.0073,
        0.0068, 0.0069, 0.0071, 0.0061, 0.0069, 0.0069, 0.0070, 0.0069, 0.0064,
        0.0063, 0.0039, 0.0046, 0.0037, 0.0074, 0.0063, 0.0060, 0.0060, 0.0067,
        0.0058, 0.0055, 0.0058, 0.0073, 0.0052, 0.0058, 0.0061, 0.0060, 0.0061,
        0.0059, 0.0058, 0.0058, 0.0048, 0.0060, 0.0064, 0.0043, 0.0041, 0.0062,
        0.0067, 0.0070, 0.0060, 0.0065, 0.0057, 0.0035, 0.0027, 0.0056, 0.0049,
        0.0078, 0.0075, 0.0031, 0.0029, 0.0030, 0.0080, 0.0078, 0.0074, 0.0077,
        0.0073, 0.0071, 0.0064, 0.0048, 0.0055, 0.0061, 0.0068, 0.0045, 0.0079,
        0.0086, 0.0084, 0.0058, 0.0029, 0.0030, 0.0027, 0.0026, 0.0026, 0.0026,
        0.0025, 0.0024, 0.0025, 0.0032, 

In [14]:
# load the dataset
from datasets import load_dataset

kr3 = load_dataset("Wittgensteinian/KR3", name='kr3', split='train')
kr3 = kr3.remove_columns(['__index_level_0__'])
kr3_binary = kr3.filter(lambda example: example['Rating'] != 2)


Using custom data configuration Wittgensteinian--KR3-9f7e41b8ab859e44
Reusing dataset parquet (/home/gsdsaml/.cache/huggingface/datasets/parquet/Wittgensteinian--KR3-9f7e41b8ab859e44/0.0.0/0b6d5799bb726b24ad7fc7be720c170d8e497f575d02d47537de9a5bac074901)
Loading cached processed dataset at /home/gsdsaml/.cache/huggingface/datasets/parquet/Wittgensteinian--KR3-9f7e41b8ab859e44/0.0.0/0b6d5799bb726b24ad7fc7be720c170d8e497f575d02d47537de9a5bac074901/cache-964db1339d22becb.arrow


In [10]:
from fresh import *

In [11]:
attn = exclude_cls_sep(attn)

In [13]:
attn

tensor([0.0000, 0.0058, 0.0062, 0.0058, 0.0061, 0.0063, 0.0068, 0.0069, 0.0070,
        0.0064, 0.0065, 0.0061, 0.0033, 0.0041, 0.0031, 0.0038, 0.0040, 0.0035,
        0.0037, 0.0026, 0.0033, 0.0032, 0.0026, 0.0036, 0.0053, 0.0026, 0.0056,
        0.0068, 0.0073, 0.0069, 0.0071, 0.0065, 0.0067, 0.0067, 0.0080, 0.0074,
        0.0069, 0.0070, 0.0072, 0.0062, 0.0070, 0.0069, 0.0071, 0.0070, 0.0065,
        0.0064, 0.0040, 0.0046, 0.0037, 0.0075, 0.0064, 0.0060, 0.0061, 0.0068,
        0.0059, 0.0056, 0.0059, 0.0074, 0.0053, 0.0058, 0.0062, 0.0061, 0.0062,
        0.0059, 0.0059, 0.0059, 0.0049, 0.0060, 0.0065, 0.0044, 0.0042, 0.0063,
        0.0068, 0.0071, 0.0061, 0.0066, 0.0058, 0.0036, 0.0028, 0.0057, 0.0050,
        0.0079, 0.0075, 0.0031, 0.0030, 0.0031, 0.0081, 0.0079, 0.0075, 0.0078,
        0.0074, 0.0072, 0.0065, 0.0049, 0.0056, 0.0061, 0.0069, 0.0046, 0.0080,
        0.0087, 0.0085, 0.0059, 0.0030, 0.0030, 0.0027, 0.0026, 0.0026, 0.0026,
        0.0025, 0.0024, 0.0025, 0.0033, 

In [20]:
from transformers import BertTokenizer

words = kr3_binary[i]['Review'].split(' ')
tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-cased')


In [21]:
words

['숙성',
 '돼지고기',
 '전문점입니다.',
 '건물',
 '모양',
 '때문에',
 '매장',
 '모양도',
 '좀',
 '특이하지만',
 '쾌적한',
 '편이고',
 '살짝',
 '레트로',
 '감성으로',
 '분위기',
 '잡아놨습니다.',
 '모든',
 '직원분들께서',
 '전부',
 '가능하다고',
 '멘트',
 '쳐주시며,',
 '고기는',
 '초반',
 '커팅까지는',
 '구워주십니다.',
 '가격',
 '저렴한',
 '편',
 '아니지만',
 '맛은',
 '준수합니다.',
 '등심덧살이',
 '인상',
 '깊었는데',
 '구이로',
 '별로일',
 '줄',
 '알았는데',
 '육향',
 '짙고',
 '얇게',
 '저며',
 '뻑뻑하지',
 '않았습니다.',
 '하이라이트는',
 '된장찌개.',
 '진짜',
 '굿입니다.',
 '버터',
 '간장밥,',
 '골뱅이',
 '국수',
 '등',
 '나중에',
 '더',
 '맛봐야',
 '할',
 '것들은',
 '남겨뒀습니다.']

In [22]:
attn_per_word = get_attn_per_word(attn, words, tokenizer)

In [24]:
attn_per_word

tensor([0.0120, 0.0182, 0.0397, 0.0073, 0.0069, 0.0040, 0.0072, 0.0092, 0.0026,
        0.0172, 0.0210, 0.0136, 0.0134, 0.0223, 0.0203, 0.0210, 0.0135, 0.0064,
        0.0322, 0.0128, 0.0173, 0.0127, 0.0243, 0.0119, 0.0108, 0.0211, 0.0387,
        0.0064, 0.0186, 0.0075, 0.0092, 0.0160, 0.0364, 0.0281, 0.0167, 0.0145,
        0.0087, 0.0078, 0.0025, 0.0082, 0.0133, 0.0161, 0.0110, 0.0061, 0.0032,
        0.0256, 0.0390, 0.0319, 0.0153, 0.0311, 0.0136, 0.0264, 0.0219, 0.0151,
        0.0073, 0.0140, 0.0073, 0.0205, 0.0064, 0.0153, 0.0414])

In [28]:
rationale, unrationale = discretize_attn(attn_per_word, words, strategy='continguous')

In [31]:
len(attn_per_word) == len(words)

True

In [29]:
rationale

['않았습니다.',
 '하이라이트는',
 '된장찌개.',
 '진짜',
 '굿입니다.',
 '버터',
 '간장밥,',
 '골뱅이',
 '국수',
 '등',
 '나중에',
 '더']

In [98]:
from glob import glob
paths = glob('outputs/FT3/attentions/batch_*.pt')

In [99]:
len(paths)

14345

In [46]:
kr3_binary[0]['Review'] = rationale

In [57]:
rationale_sentence = ' '.join(rationale)
rationale_sentence

'않았습니다. 하이라이트는 된장찌개. 진짜 굿입니다. 버터 간장밥, 골뱅이 국수 등 나중에 더'

In [85]:
kr3_rationale = Dataset.from_dict({}

AttributeError: 'list' object has no attribute 'encode_batch'

In [84]:
kr3

Dataset({
    features: ['Rating', 'Review'],
    num_rows: 641762
})

In [91]:
kr3_rationale = kr3_rationale.add_item({'Rating':1, 'Rationale':rationale_sentence})

In [92]:
kr3_rationale[0]

{'Rating': 1,
 'Rationale': '않았습니다. 하이라이트는 된장찌개. 진짜 굿입니다. 버터 간장밥, 골뱅이 국수 등 나중에 더'}

In [80]:
tokenizer(rationale_sentence)

{'input_ids': [101, 9523, 119118, 119081, 48345, 119, 9952, 10739, 17342, 41620, 11018, 9099, 13890, 119245, 21789, 119, 9708, 119235, 8915, 58303, 48345, 119, 9336, 21876, 8845, 13890, 118969, 117, 8892, 118974, 10739, 8909, 15891, 9121, 8982, 81724, 9074, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}