In [24]:
import torch

In [8]:
# load the dataset
from datasets import load_dataset

kr3 = load_dataset("Wittgensteinian/KR3", name='kr3', split='train')
kr3 = kr3.remove_columns(['__index_level_0__'])
kr3_binary = kr3.filter(lambda example: example['Rating'] != 2)


Using custom data configuration Wittgensteinian--KR3-0f424e029f3cf821
Reusing dataset parquet (/home/gsdsaml/.cache/huggingface/datasets/parquet/Wittgensteinian--KR3-0f424e029f3cf821/0.0.0/0b6d5799bb726b24ad7fc7be720c170d8e497f575d02d47537de9a5bac074901)
Loading cached processed dataset at /home/gsdsaml/.cache/huggingface/datasets/parquet/Wittgensteinian--KR3-0f424e029f3cf821/0.0.0/0b6d5799bb726b24ad7fc7be720c170d8e497f575d02d47537de9a5bac074901/cache-88ae1594470bd0c3.arrow


In [9]:
from transformers import BertTokenizer

tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-cased')

In [11]:
batch_i = 9
attns = torch.load(f'outputs/FT3/attentions/batch_{batch_i}.pt')
logits = torch.load(f'outputs/FT3/logits/batch_{batch_i}.pt')
print(attns.size())


torch.Size([32, 12, 134])


In [12]:
example_i = 15
attn = attns[example_i][-1]
attn, attn.count_nonzero()

(tensor([0.0077, 0.0076, 0.0076, 0.0075, 0.0076, 0.0076, 0.0075, 0.0075, 0.0074,
         0.0076, 0.0076, 0.0078, 0.0078, 0.0077, 0.0075, 0.0076, 0.0073, 0.0076,
         0.0074, 0.0075, 0.0073, 0.0074, 0.0074, 0.0073, 0.0067, 0.0075, 0.0071,
         0.0068, 0.0073, 0.0077, 0.0077, 0.0076, 0.0078, 0.0075, 0.0074, 0.0073,
         0.0071, 0.0075, 0.0074, 0.0075, 0.0076, 0.0075, 0.0075, 0.0076, 0.0075,
         0.0075, 0.0076, 0.0077, 0.0076, 0.0076, 0.0079, 0.0076, 0.0065, 0.0062,
         0.0092, 0.0092, 0.0082, 0.0073, 0.0076, 0.0069, 0.0077, 0.0078, 0.0084,
         0.0083, 0.0072, 0.0055, 0.0070, 0.0067, 0.0060, 0.0070, 0.0073, 0.0073,
         0.0072, 0.0075, 0.0075, 0.0073, 0.0075, 0.0076, 0.0076, 0.0075, 0.0075,
         0.0076, 0.0076, 0.0077, 0.0075, 0.0075, 0.0073, 0.0069, 0.0067, 0.0075,
         0.0076, 0.0076, 0.0077, 0.0077, 0.0077, 0.0077, 0.0074, 0.0076, 0.0074,
         0.0072, 0.0059, 0.0066, 0.0057, 0.0062, 0.0067, 0.0064, 0.0074, 0.0075,
         0.0076, 0.0076, 0.0

In [13]:
tokenized = tokenizer(kr3_binary[batch_i*32 + example_i]['Review'])

In [14]:
len(tokenized['input_ids'])

134

In [15]:
from fresh_extract import *

In [16]:
attn = exclude_cls_sep(attn)

In [17]:
attn

tensor([0.0000, 0.0077, 0.0077, 0.0076, 0.0077, 0.0077, 0.0077, 0.0076, 0.0075,
        0.0077, 0.0077, 0.0079, 0.0080, 0.0078, 0.0076, 0.0077, 0.0074, 0.0077,
        0.0075, 0.0076, 0.0074, 0.0075, 0.0075, 0.0074, 0.0068, 0.0076, 0.0072,
        0.0069, 0.0074, 0.0078, 0.0078, 0.0077, 0.0079, 0.0076, 0.0075, 0.0075,
        0.0072, 0.0076, 0.0076, 0.0076, 0.0077, 0.0076, 0.0076, 0.0077, 0.0076,
        0.0076, 0.0077, 0.0078, 0.0078, 0.0077, 0.0080, 0.0077, 0.0066, 0.0063,
        0.0094, 0.0093, 0.0083, 0.0074, 0.0077, 0.0070, 0.0078, 0.0079, 0.0085,
        0.0084, 0.0073, 0.0056, 0.0071, 0.0068, 0.0060, 0.0071, 0.0075, 0.0075,
        0.0073, 0.0076, 0.0076, 0.0074, 0.0077, 0.0077, 0.0077, 0.0077, 0.0076,
        0.0077, 0.0077, 0.0078, 0.0076, 0.0076, 0.0075, 0.0070, 0.0068, 0.0076,
        0.0078, 0.0078, 0.0078, 0.0078, 0.0079, 0.0078, 0.0075, 0.0077, 0.0075,
        0.0073, 0.0059, 0.0067, 0.0058, 0.0063, 0.0068, 0.0065, 0.0075, 0.0076,
        0.0077, 0.0078, 0.0079, 0.0079, 

In [18]:
words = kr3_binary[batch_i*32 + example_i]['Review'].split(' ')
words

['여기',
 '탕수육과',
 '짜장면,',
 '맛있다.',
 '평소',
 '배달해',
 '먹던',
 '중식과',
 '다른,',
 '바깥에서',
 '깔끔한',
 '중식당에',
 '갔을',
 '때',
 '무심코',
 '기대해보는',
 '딱',
 '그런',
 '맛.',
 '무슨',
 '호텔',
 '중식당',
 '이런',
 '맛에는',
 '미치지',
 '못하겠지만',
 '이',
 '주변에서',
 '자신',
 '있게',
 '손님을',
 '데려갈',
 '수',
 '있는',
 '중식당이라면',
 '여기라고',
 '생각.',
 '기본',
 '식수가',
 '맹물이',
 '아닌',
 '차갑게',
 '식힌',
 '국화',
 '차인',
 '것도',
 '좋음.',
 '식후에는',
 '입가심으로',
 '홍초',
 '물',
 '같은',
 '것을',
 '준다.']

In [19]:
import torch

In [20]:
t = torch.Tensor([.1,.1,.1,.0,.0,.0,.0,])

In [21]:
t.nonzero().squeeze()[-1].item()
# t[t.nonzero().squeeze()]

2

In [22]:
t[:3]

tensor([0.1000, 0.1000, 0.1000])

In [23]:
attn_per_word = get_attn_per_word(attn, words, tokenizer)

In [24]:
attn_per_word

tensor([0.0155, 0.0307, 0.0307, 0.0237, 0.0153, 0.0226, 0.0150, 0.0224, 0.0144,
        0.0215, 0.0234, 0.0305, 0.0148, 0.0076, 0.0229, 0.0382, 0.0078, 0.0155,
        0.0157, 0.0129, 0.0187, 0.0235, 0.0070, 0.0157, 0.0242, 0.0256, 0.0071,
        0.0222, 0.0152, 0.0074, 0.0230, 0.0230, 0.0077, 0.0078, 0.0441, 0.0233,
        0.0234, 0.0153, 0.0148, 0.0185, 0.0063, 0.0208, 0.0153, 0.0157, 0.0155,
        0.0155, 0.0235, 0.0241, 0.0316, 0.0154, 0.0077, 0.0080, 0.0081, 0.0239])

In [29]:
rationale, unrationale = discretize_attn(attn_per_word, words, strategy='Top-k')

In [30]:
len(attn_per_word) == len(words)

True

In [31]:
rationale

['탕수육과',
 '짜장면,',
 '중식당에',
 '기대해보는',
 '미치지',
 '못하겠지만',
 '중식당이라면',
 '식후에는',
 '입가심으로',
 '준다.']

In [28]:
unrationale

['여기',
 '중식당에',
 '갔을',
 '때',
 '무심코',
 '기대해보는',
 '딱',
 '그런',
 '맛.',
 '무슨',
 '호텔',
 '중식당',
 '이런',
 '맛에는',
 '미치지',
 '못하겠지만',
 '이',
 '주변에서',
 '자신',
 '있게',
 '손님을',
 '데려갈',
 '수',
 '있는',
 '중식당이라면',
 '여기라고',
 '생각.',
 '기본',
 '식수가',
 '맹물이',
 '아닌',
 '차갑게',
 '식힌',
 '국화',
 '차인',
 '것도',
 '좋음.',
 '식후에는',
 '입가심으로',
 '홍초',
 '물',
 '같은',
 '것을',
 '준다.']

In [20]:
rating = kr3_binary[batch_i*32 + example_i]['Rating']
rating

1

### Saving into dataset

In [33]:
from datasets import Dataset
dataset = Dataset.from_dict({})

In [34]:
dataset = dataset.add_item({'Rating':1, 'Rationale':' '.join(rationale), 'Unrationale':' '.join(unrationale)})

In [35]:
dataset[0]

{'Rating': 1,
 'Rationale': '탕수육과 짜장면, 맛있다. 평소 배달해 먹던 중식과 다른, 바깥에서 깔끔한',
 'Unrationale': '여기 중식당에 갔을 때 무심코 기대해보는 딱 그런 맛. 무슨 호텔 중식당 이런 맛에는 미치지 못하겠지만 이 주변에서 자신 있게 손님을 데려갈 수 있는 중식당이라면 여기라고 생각. 기본 식수가 맹물이 아닌 차갑게 식힌 국화 차인 것도 좋음. 식후에는 입가심으로 홍초 물 같은 것을 준다.'}

In [36]:
' '.join(words)

'여기 탕수육과 짜장면, 맛있다. 평소 배달해 먹던 중식과 다른, 바깥에서 깔끔한 중식당에 갔을 때 무심코 기대해보는 딱 그런 맛. 무슨 호텔 중식당 이런 맛에는 미치지 못하겠지만 이 주변에서 자신 있게 손님을 데려갈 수 있는 중식당이라면 여기라고 생각. 기본 식수가 맹물이 아닌 차갑게 식힌 국화 차인 것도 좋음. 식후에는 입가심으로 홍초 물 같은 것을 준다.'